'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsR
    Inherits DataSet
    
    Private tableXRows As XRowsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("XRows")) Is Nothing) Then
                Me.Tables.Add(New XRowsDataTable(ds.Tables("XRows")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property XRows As XRowsDataTable
        Get
            Return Me.tableXRows
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsR = CType(MyBase.Clone,dsR)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("XRows")) Is Nothing) Then
            Me.Tables.Add(New XRowsDataTable(ds.Tables("XRows")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableXRows = CType(Me.Tables("XRows"),XRowsDataTable)
        If (Not (Me.tableXRows) Is Nothing) Then
            Me.tableXRows.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsR"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsR.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableXRows = New XRowsDataTable
        Me.Tables.Add(Me.tableXRows)
    End Sub
    
    Private Function ShouldSerializeXRows() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub XRowsRowChangeEventHandler(ByVal sender As Object, ByVal e As XRowsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class XRowsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnRow As DataColumn
        
        Private columnXData As DataColumn
        
        Friend Sub New()
            MyBase.New("XRows")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property RowColumn As DataColumn
            Get
                Return Me.columnRow
            End Get
        End Property
        
        Friend ReadOnly Property XDataColumn As DataColumn
            Get
                Return Me.columnXData
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As XRowsRow
            Get
                Return CType(Me.Rows(index),XRowsRow)
            End Get
        End Property
        
        Public Event XRowsRowChanged As XRowsRowChangeEventHandler
        
        Public Event XRowsRowChanging As XRowsRowChangeEventHandler
        
        Public Event XRowsRowDeleted As XRowsRowChangeEventHandler
        
        Public Event XRowsRowDeleting As XRowsRowChangeEventHandler
        
        Public Overloads Sub AddXRowsRow(ByVal row As XRowsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddXRowsRow(ByVal XData As String) As XRowsRow
            Dim rowXRowsRow As XRowsRow = CType(Me.NewRow,XRowsRow)
            rowXRowsRow.ItemArray = New Object() {Nothing, XData}
            Me.Rows.Add(rowXRowsRow)
            Return rowXRowsRow
        End Function
        
        Public Function FindByRow(ByVal Row As Integer) As XRowsRow
            Return CType(Me.Rows.Find(New Object() {Row}),XRowsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As XRowsDataTable = CType(MyBase.Clone,XRowsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New XRowsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnRow = Me.Columns("Row")
            Me.columnXData = Me.Columns("XData")
        End Sub
        
        Private Sub InitClass()
            Me.columnRow = New DataColumn("Row", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnRow)
            Me.columnXData = New DataColumn("XData", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnXData)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnRow}, true))
            Me.columnRow.AutoIncrement = true
            Me.columnRow.AllowDBNull = false
            Me.columnRow.ReadOnly = true
            Me.columnRow.Unique = true
        End Sub
        
        Public Function NewXRowsRow() As XRowsRow
            Return CType(Me.NewRow,XRowsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New XRowsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(XRowsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.XRowsRowChangedEvent) Is Nothing) Then
                RaiseEvent XRowsRowChanged(Me, New XRowsRowChangeEvent(CType(e.Row,XRowsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.XRowsRowChangingEvent) Is Nothing) Then
                RaiseEvent XRowsRowChanging(Me, New XRowsRowChangeEvent(CType(e.Row,XRowsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.XRowsRowDeletedEvent) Is Nothing) Then
                RaiseEvent XRowsRowDeleted(Me, New XRowsRowChangeEvent(CType(e.Row,XRowsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.XRowsRowDeletingEvent) Is Nothing) Then
                RaiseEvent XRowsRowDeleting(Me, New XRowsRowChangeEvent(CType(e.Row,XRowsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveXRowsRow(ByVal row As XRowsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class XRowsRow
        Inherits DataRow
        
        Private tableXRows As XRowsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableXRows = CType(Me.Table,XRowsDataTable)
        End Sub
        
        Public Property Row As Integer
            Get
                Return CType(Me(Me.tableXRows.RowColumn),Integer)
            End Get
            Set
                Me(Me.tableXRows.RowColumn) = value
            End Set
        End Property
        
        Public Property XData As String
            Get
                Try 
                    Return CType(Me(Me.tableXRows.XDataColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableXRows.XDataColumn) = value
            End Set
        End Property
        
        Public Function IsXDataNull() As Boolean
            Return Me.IsNull(Me.tableXRows.XDataColumn)
        End Function
        
        Public Sub SetXDataNull()
            Me(Me.tableXRows.XDataColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class XRowsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As XRowsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As XRowsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As XRowsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
